### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylor** [Adalab/modulo-3-evaluacion-intermedia-Laura-Carbajales#1]
Buen trabajo @Laura-Carbajales  !

### Algunas pistas para mejorarlo:

- [x] Modifica el filter por tutora para que sea más genérico y el código no esté asociado a tutores fijos, y agrega que se pueda filtrar por todos.: https://github.com/Adalab/modulo-3-evaluacion-intermedia-Laura-Carbajales/blob/abe633ca627566311f575d3be021f016a31064da/src/components/App.js#L23-L31 

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by Laura-Carbajales** [comment]
Solved Issue! :)
